---
abstract: 'Iteration data with Sliding Window Algorithm'
author:
  - 'Hideaki Ohno <hide.o.j55{at}gmail.com>'
build_requires:
  Test::Fatal: '0.008'
  Test::More: '0.98'
configure_requires:
  CPAN::Meta: '0'
  CPAN::Meta::Prereqs: '0'
  Module::Build: '0.38'
dynamic_config: 0
generated_by: 'Minilla/v1.1.0, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Data-Iterator-SlidingWindow
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Data::Iterator::SlidingWindow:
    file: lib/Data/Iterator/SlidingWindow.pm
    version: '0.05'
requires:
  Exporter: '0'
  parent: '0'
  perl: '5.008001'
resources:
  bugtracker: https://github.com/hideo55/Data-Iterator-SlidingWindow/issues
  homepage: https://github.com/hideo55/Data-Iterator-SlidingWindow
  repository: git://github.com/hideo55/Data-Iterator-SlidingWindow.git
version: '0.05'
x_contributors:
  - 'hideo55 <hide.o.j55@gmail.com>'
